# Structuring your project

The scientific process is naturally incremental, and many projects start
life as random notes, some code, then a manuscript, and eventually everything
is a bit mixed together. It does not have to be like that.

Objectives:

* To be able to create self-contained projects in RStudio
* To be able to transfer things from the console to a file
* To be able to create a R markdown document


## Projects

Creating a new project in R. How to organise folders.

XXX https://github.com/swcarpentry/r-novice-gapminder/blob/gh-pages/_episodes/02-project-intro.md


## Interactive work vs scripts

Move from interactive work to a script. Why? How?


## Reports

Humans understand the world through narratives, or stories. Figures, tables
and code by themselves do not tell a story. They are more like a collection of
factoids. However a story without figures, tables and code is just a rumour or
folklore. The combination of facts and narrative is what allows people to
understand and be convinced.

One way to combine your narrative with figures and tables is
[Rmarkdown](http://rmarkdown.rstudio.com/lesson-1.html). You can use a single
Rmarkdown file to both:

* save and execute code; and
* generate high quality reports that can be shared with people who do not have
  R installed.

In fact most of this tutorial is written using Rmarkdown!

> ## R notebooks
>
> At the start of October RStudio gained a ["R notebook"
> interface](https://www.r-bloggers.com/r-notebooks/). If you like Rmarkdown
> check it out in the preview release of RStudio.

There are several different output formats you can choose: HTML, PDF, Word.
Depending on how much time you are willing to invest you can make these
reports look extremely pretty. They are very useful for reports that change
often or need to be produced frequently. Personally I would still give the
individual plots to a graphic designer for a external publication, but for
sharing within the organisation and friends Rmarkdown is a life saver. It
means you always know exactly what data went into a figure or table and how
it was made.

> ## Output options
>
> Chunk output can be customized with [knitr](http://yihui.name/knitr/options/)
> options, arguments set in the `{}` of a chunk header. Five useful arguments:
>
> * include = FALSE prevents code and results from appearing in the
>   finished file. Rmarkdown still runs the code in the chunk, and the
>   results can be used by other chunks.
> * echo = FALSE prevents code, but not the results from appearing in
>   the finished file. This is a useful way to embed figures.
> * message = FALSE prevents messages that are generated by code from
>   appearing in the finished file.
> * warning = FALSE prevents warnings that are generated by code from
>   appearing in the finished.
> * fig.cap = "..." adds a caption to graphical results.
>
> Check the [R Markdown Reference
> Guide](https://www.rstudio.com/wp-content/uploads/2015/03/rmarkdown-reference.pdf) for more knitr
> options.
