# How to get unstuck

Eventually you will get stuck when trying to do something.
This lesson is about how to get help with getting unstuck.

Objectives:

* To understand the need for a minimal working example
* To be able to find the documentation for a library
* To be able to ask a good question


## The psychology of asking questions

People love helping others. Below some tips on how to improve
your chances of getting a good answer. The answers you get
will depend very much on the way you ask your question.

> ## Shorthand
>
> This document uses "mailing list" as a shorthand for "all kinds
> of written communication on the internet". Replace with forum,
> Stack Overflow, Slack, Skype as appropriate.

The title/subject is the first thing people will see of your
question. If it is not interesting, they will not read the rest.
If you are struggling with a good title, write it last! Having
written the rest of your email will give you a better idea of what
the one sentence summary is.

> ## Grammar and spelling
>
> This is a no brainer. You want to make a good impression:
> someone who made an effort and values other people's time.
> If you are not comfortable with writing in English, ask a friend
> to proof-read your email/message for you.

Most people like hard problems and thought-provoking questions. So
give them an interesting question to chew on, and they will love it.

Despite this, mailing lists have a reputation for a hostile tone and
an air of arrogance. People are hostile towards people who seem unwilling
to think for themselves or did not do their homework before asking their
question.

> ## Volunteers
>
> Remember people are volunteering their time to help you. They have busy
> lives and there are a lot of questions. So they filter ruthlessly. Make
> sure your question is the most interesting one out there, and people
> will choose to help you.

It is OK that you are not technically competent, what you need to show is
that you have the skills to become competent: alert, thoughtful, observant,
willing to be an active partner in developing a solution.

Before posting your question try:

1. searching the archives of the forum/mailing list
2. searching the web
3. finding the answer in a FAQ
4. finding the answer by experimenting
5. asking a skilled friend
6. or reading the code

When asking your question, mention which of these steps you have tried. It
will help demonstrate that you are not lazy and put in some effort. If you
learnt something from trying this, mention it!

The beginning of your email should explain what you are trying to do and
why, as well as where the problem occurs. Often it is useful to describe
the big goal, and not the particular step you are stuck with.

Help others reproduce your problem by including the necessary details. If
the problem is with code you wrote, include it. However do not post all of your
program. Try and make a minimal example that demonstrates the problem. Stack
Overflow has a good guide on creating a [minimal, complete, and verifiable
example](http://stackoverflow.com/help/mcve).

You have to be precise. Do not simply dump all possible information that
might be relevant. Vague questions receive vague answers. Being precise is
useful for at least three reasons. (1) Being seen to invest effort in simplifying
the question makes it more likely you'll get an answer (2) Simplifying
the question makes it more likely you'll get a useful answer. (3) In
the process of refining your bug report, you may develop a fix or workaround yourself.

When people post replies or questions about your problem, follow them up. If
you manage to solve your problem, tell the mailing list.

> ## Love letters also known as private replies {.callout}
>
> Please do not reply to questions privately. We are trying to solve a technical
> issue, not writing lover letters. If you take the discussion
> off the mailing list future generations will just see the question and no
> solution. You will also miss out on help from others that did not chime
> in to your first question but might be able to help later on.

Once the problem is solved post a final message saying that the problem is
solved and what the solution is.

A lot of the material in this topic was taken from the following, excellent
guides to asking good questions:

 * [How To Ask Questions The Smart Way](http://www.catb.org/esr/faqs/smart-questions.html) by
   Eric Raymond
 * [Writing the perfect question](http://codeblog.jonskeet.uk/2010/08/29/writing-the-perfect-question/)
   by Jon Skeet
 * [How do I ask a good question?](http://stackoverflow.com/help/how-to-ask) on Stack Overflow

## Where to go

This is a list of resources to help you find answers and examples:

* Take a look at `Help > Cheatsheets` in RStudio
* [Statistics StackOverflow](http://stats.stackexchange.com/): focuses on
  statistics, but statistics geeks use R!
* [Google](http://google.com): how strong is your google-fu?
* [R project's "where to get help"](https://www.r-project.org/help.html): links
  to lots of useful resources
* a mailing list/chat inside your organisation: good place to go for very, very,
  specific questions.
* [The Comprehensive R Archive Network](https://cran.r-project.org/): every
  library is listed here with examples (vignette) and documentation


## Other Resources
As mentioned earlier, there are TOO many resources to mention and everyone
has their favorites.  Below just a few:

- [R For Cats](http://rforcats.net/): Basic introduction site, meant to be a gentle and light-hearted introduction
- [Advanced R](http://adv-r.had.co.nz/): Web home of Hadley Wickham's new book.  Gets into more advanced topics, but also covers the basics in a great way.
- [Why R is Hard To Learn](http://r4stats.com/articles/why-r-is-hard-to-learn/): Long and detailed blog post discussing some of the challenges people often face when learning R.
- [CRAN Cheatsheets](http://cran.r-project.org/doc/contrib/Short-refcard.pdf): A good cheat sheet from the official source
- [RStudio Cheatsheets](http://www.rstudio.com/resources/cheatsheets/): Additional cheat sheets from RStudio. Check out the data wrangling one.
